### ISSUE TITLE
BillboardTextBundle crashes when sharing a font with bevy's TextBundle

### ISSUE THREAD

**Issue by robtfm** [kulkalkul/bevy_mod_billboard#10]
when i used a `BillboardTextBundle` together with a bevy-builtin `TextBundle` i get :

```
thread 'Compute Task Pool (7)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `ui_material_bind_group`
    texture usage is COPY_SRC | COPY_DST which does not contain required usage TEXTURE_BINDING
```

i can replicate this by adding the line :
```rust
commands.spawn(TextBundle::from_section("ui text", TextStyle { font: fira_sans_regular_handle.clone(), font_size: 60.0, color: Color::BLACK }));
```

to the `text.rs` example at the end of the setup function.

it only occurs when the `TextStyle` matches exactly on font and size (so my easy workaround for now is to use a billboard font size that isn't used by my ui).

windows / nvidia / vulkan / bevy 0.10.1/ bevy_mod_billboard 0.3.0

thanks!

**Comment by kulkalkul** [comment]
Thanks! Unfortunately, I don't have much time nowadays, but I'll investigate this at some point, maybe closer to Bevy's 0.11
