### ISSUE TITLE
Locking other axis

### ISSUE THREAD

**Issue by nixpulvis** [kulkalkul/bevy_mod_billboard#28]
I'm building a program in 3D and I'd really like to have text which is always facing the camera regardless of camera rotation around of text.

Is this possible?

**Comment by kulkalkul** [comment]
Not sure if I understand the behaviour you want. Can you show a screenshot of the behaviour you currently get?

**Comment by nixpulvis** [comment]
Here's it from the side(s):
![screenshot-2024-08-25T16:21:49Z](https://github.com/user-attachments/assets/f485c8b7-e86c-4e51-b107-98456ba114b5)
![screenshot-2024-08-25T16:21:30Z](https://github.com/user-attachments/assets/954f0946-ed98-4a93-aea7-c65307b7e604)

From the top it becomes invisible:

![screenshot-2024-08-25T16:22:07Z](https://github.com/user-attachments/assets/05012397-51f5-4725-87cc-5d1395d90e44)

**Comment by kulkalkul** [comment]
I moved camera in example/text.rs to higher place to test it, can't reproduce:
![image](https://github.com/user-attachments/assets/5670526d-5945-48d9-9574-b2eea43e8142)

The behaviour I see from your screenshot looks like y locked. Is there a chance of it being Y locked?

**Comment by nixpulvis** [comment]
OK, I feel stupid. I read the docs assumed I needed axis locking and never tried the default.

Sorry for the noise. Thanks for the plugin! Now I just need to get the font to be crisp like yours and I'm golden.

**Comment by kulkalkul** [comment]
Ah, no worries; I should've documented it better; it totally lacks any documentation except examples directory 😅
