### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by alice-i-cecile** [kulkalkul/bevy_mod_billboard#4]
When working on https://github.com/Leafwing-Studios/Emergence/pull/613, I encountered a memory leak, which ultimately led to a panic due to my GPU running out of memory.

This was the commit in question: https://github.com/Leafwing-Studios/Emergence/pull/613/commits/0f60c50a763f7d511e250f59a323ececaad6381d

Here's what my system monitor looked like, before and after toggling on the billboarded text via the F2 key.

![image](https://user-images.githubusercontent.com/3579909/228378300-f5e35a3d-f46c-4140-ab61-b4fe6acd14c6.png)

The drop is when the game crashed 😅 

I'm using this in a simple immediate mode way for now, as seen [here](https://github.com/Leafwing-Studios/Emergence/pull/613/files#diff-1d82eb57924c3cc05bc4a14ed7b054a481f9ab3fb3dc9e8fa90d4dc702ffdf06R49), but I *am* being careful to reuse assets and despawn my entities each frame.

**Comment by kulkalkul** [comment]
I was afraid of the possibility this would happen 😅
