### ISSUE TITLE
Converting from Handle<Image> requires duplicate asset tracking

### ISSUE THREAD

**Issue by alice-i-cecile** [kulkalkul/bevy_mod_billboard#7]
I want to reuse a png for both UI icons and a billboarded status display. Because this plugin requires `Handle<BillBoardTexture>` rather than a `Handle<Image>`, I have to store two separate collections.

Options:

1. Just use `Handle<Image>` everywhere (and do the same for `Mesh`).
2. `impl From<Handle<Image>> for Handle<BillboardTexture>`

**Comment by kulkalkul** [comment]
I don't recall the exact reason but BillboardTexture was necessary for a reason, so I'd prefer the latter option. Though I'm not sure if that solves it, doesn't it still require a clone to work? I'd be glad to merge if you have an existing solution in your mind that works for you 😅.

**Comment by kulkalkul** [comment]
~~I wonder if it is possible to cast handles that way, I recall some handle function related to casting. Though I'm not in a position to test it rn, unfortunately 🙁~~

Though, that doesn't make sense; types are different... My bad.

**Comment by alice-i-cecile** [comment]
I suspect you couldn't do 1 as your types were getting picked up by Bevy's existing systems.

I *think* 2 should work just fine: I'll make a PR in the next few days.

**Comment by kulkalkul** [comment]
Thanks, appreaciate that! I'm not working with bevy nowadays, migrated to godot for my first project, so my time is scarce. Though I still want to maintain the crate and return to the bevy at some point later (after my first game, preferably).

**Comment by alice-i-cecile** [comment]
Ah: this can just be done by creating a [HandleUntyped](https://docs.rs/bevy/latest/bevy/asset/struct.HandleUntyped.html) via `clone_untyped` on your original handle, and then calling `typed` / `typed_weak` on it.

No special code needed here!
